### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ghost** [AdyaGMD/IngameListMod#4]
The game will crash if i try to download songs, delete a level or change its location folder in the saved levels menu.
I will attach the log and a video (beware of volume).

https://github.com/AdyaGMD/IngameListMod/assets/160338409/2b71a297-1400-4e4d-9c04-e8872abea7d5

[2024-02-17_16-42-06.log](https://github.com/AdyaGMD/IngameListMod/files/14319372/2024-02-17_16-42-06.log)

**Comment by AdyaGMD** [comment]
it was an issue with platformer levels, fixed

**Comment by ghost** [comment]
thanks
