### ISSUE TITLE
Plattformer levels crash when you opened them with InGameListMod

### ISSUE THREAD

**Issue by JoJoBollo** [AdyaGMD/IngameListMod#5]
If you tried to play a level with
 the mod it will instantly crash, plz check it <3
Here's the error log: 
[2024-02-17_17-16-41.log](https://github.com/AdyaGMD/IngameListMod/files/14320072/2024-02-17_17-16-41.log)
This is the error screen that pops out when the game dies
![imagen_2024-02-17_204711024](https://github.com/AdyaGMD/IngameListMod/assets/160356042/d58fc2f2-4c84-4753-8ed4-e17d9afce907)

**Comment by AdyaGMD** [comment]
fixed, waiting for geode devs to accept the update
