### ISSUE TITLE
Won't show up any top ranking after new github update

### ISSUE THREAD

**Issue by JoJoBollo** [AdyaGMD/IngameListMod#6]
After the crash fix update that you put on github (the fix works), now it doesn't show any top ranking in any type of level.
Here are some examples:

![image](https://github.com/AdyaGMD/IngameListMod/assets/160356042/fb53f624-44ad-4e01-92a2-671e6624a30a)
![image](https://github.com/AdyaGMD/IngameListMod/assets/160356042/3a63956c-be71-4df1-9749-85828bdb192c)
![image](https://github.com/AdyaGMD/IngameListMod/assets/160356042/8a059294-0c47-4820-9cbb-804ec49ec5e5)
![image](https://github.com/AdyaGMD/IngameListMod/assets/160356042/2b6d6169-3041-401e-a89a-80e54350889a)

And other thing,(for curiosity), from which website, data, etc you get the list for the extreme demon rankings?

**Comment by AdyaGMD** [comment]
download the mod from releases again, I fixed that

**Comment by AdyaGMD** [comment]
by the way I get data from the AREDL, the challenge list and the platformerlist
